route:
  receiver: default
  group_by: ['alertname']
  group_wait: 30s
  repeat_interval: 4h

receivers:
  - name: default
    webhook_configs:
      - url: http://send-router:4000/api/hooks/alerts
        send_resolved: true
