version: "3.9"

services:
  caddy:
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - ../config/caddy/Caddyfile.local:/etc/caddy/Caddyfile:ro

  keycloak:
    environment:
      PROXY_ADDRESS_FORWARDING: "true"

  element:
    environment:
      - PUBLIC_BASE_URL=${PUBLIC_SCHEME:-http}://${CHAT_FQDN}
